name: Backup Main Branch (SSH) to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  backup-main-to-azure-devops:
    name: Backup `main` branch to secondary repository using SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Actions"
          git config user.email "actions@github.com"

      - name: Set Up SSH for Backup Repo
        env:
          SSH_PRIVATE_KEY: ${{ secrets.BACKUP_REPO_AZURE_DEVOPS_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Optional: Disable host key checking for automation (only if host is trusted)
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

          # Ensure ssh-agent is running
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Add SSH Remote and Push `main` Branch
        env:
          REMOTE_REPO_URL: ${{ secrets.BACKUP_REPO_AZURE_DEVOPS_REPO_URL }}
        run: |
          git remote add backup "${REMOTE_REPO_URL}"
          git push --force backup main:main
